name: SheikhLLM Runner

on:
  schedule:
    # Run weekly on Monday at 1:00 AM UTC
    - cron: '0 1 * * 1'
  workflow_dispatch:
    inputs:
      dataset:
        description: 'Dataset to use for fine-tuning'
        required: false
        default: 'truthful_qa'
        type: choice
        options:
          - truthful_qa
          - squad
          - drop
          - toxicity
          - tldr
      epochs:
        description: 'Number of training epochs'
        required: false
        default: '3'
        type: string
      learning_rate:
        description: 'Learning rate for fine-tuning'
        required: false
        default: '2e-5'
        type: string

jobs:
  fine-tune:
    runs-on: ubuntu-latest
    name: Fine-tune SheikhLLM Model
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure Together API
        run: |
          echo "TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }}" > .env
          
      - name: Run fine-tuning
        run: |
          python fine_tune_sheikhllm.py \
            --dataset ${{ github.event.inputs.dataset || 'truthful_qa' }} \
            --epochs ${{ github.event.inputs.epochs || 3 }} \
            --learning_rate ${{ github.event.inputs.learning_rate || '2e-5' }} \
            --use_real_api
          
      - name: Save model ID
        run: |
          MODEL_ID=$(grep -o "ft-[a-zA-Z0-9]*" fine_tuning_output/job_info.txt | head -1)
          echo "MODEL_ID=$MODEL_ID" >> $GITHUB_ENV
          echo "Fine-tuned model ID: $MODEL_ID"
          
      - name: Validate model
        run: |
          echo "Running validation tests on fine-tuned model"
          python use_sheikhllm.py --model_id ${{ env.MODEL_ID }} --test_mode True --prompt "What is the capital of France?"
          
      - name: Upload training artifacts
        uses: actions/upload-artifact@v3
        with:
          name: training-artifacts
          path: fine_tuning_output/
          retention-days: 7
